apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: goprom-canary
  labels:
    app: goprom
  annotations:
    kubernetes.io/ingress.class: "nginx"

    # Enable canary and send 10% of traffic to version 2
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  rules:
  - host: goprom.com
    http:
      paths:
      - backend:
          serviceName: goprom-v2
          servicePort: 80
